### ISSUE TITLE
The data with the same group id is discarded by the platform and unsolved

### ISSUE THREAD

**Issue by SeeedWenzy** [SeeedJP/Wio_Tracker_1110_Examples#3]
<img width="1414" alt="1" src="https://github.com/SeeedJP/Wio_Tracker_1110_Examples/assets/142080102/5cf9ba39-2bfd-4df3-bc8e-270de82049ee">
<img width="1211" alt="2" src="https://github.com/SeeedJP/Wio_Tracker_1110_Examples/assets/142080102/380e7f49-a250-4dae-8e4f-090c5c5284c7">

 datas from 2023-08-24 21:30:18~ 2023-08-24 21:51:18 loss

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Adafruit_nRF52_Arduino/commit/5e30b81ce4e227eae6db20f6f896f04fa181f22b
